[theme]
# Primary accent color - muted cyan for links/buttons
primaryColor = "#5DADE2"

# Background color for the main content area - dark charcoal
backgroundColor = "#1A1A1A"

# Background color for sidebar - slightly lighter dark
secondaryBackgroundColor = "#252525"

# Color used for almost all text - light gray for readability
textColor = "#E0E0E0"

# Font family for all text
font = "serif"

# Base font size
base = "light"

[server]
# Port to run the app on
port = 8501

# Enable file watching
runOnSave = true

[browser]
# Tab title
gatherUsageStats = false
